import { Component } from '@angular/core';

@Component({
  selector: 'app-chatbot',
  templateUrl: './chatbot.component.html',
  styleUrls: ['./chatbot.component.css']
})
export class ChatbotComponent {
  userMessage: string = '';
  botResponse: string = '';
  messages: { user: string, bot: string }[] = [];
  isChatbotVisible: boolean = true; // Variable pour gérer la visibilité du chatbot

  // Base de données des mots-clés et réponses correspondantes
  private responseDatabase = [
    { keyword: 'horaires', response: 'Nos horaires d\'ouverture sont de 9h à 18h, du lundi au vendredi.' },
    { keyword: 'horaire', response: 'Nos horaires d\'ouverture sont de 9h à 18h, du lundi au vendredi.' },
     { keyword: 'contact', response: 'Vous pouvez nous contacter par email à ismaia.barry@esprit.tn ou 0021628628416.' },
    { keyword: 'contacter', response: 'Vous pouvez nous contacter par email à ismaia.barry@esprit.tn ou 0021628628416.' },
    { keyword: 'produit', response: 'Nous avons une large gamme de produits électroniques, y compris des téléphones, des ordinateurs portables, et des accessoires.' },
    { keyword: 'produits', response: 'Nous avons une large gamme de produits électroniques, y compris des téléphones, des ordinateurs portables, et des accessoires.' },
    { keyword: 'retour', response: 'Si vous souhaitez retourner un produit, veuillez nous contacter dans un délai de 30 jours suivant l\'achat.' },
    { keyword: 'prix', response: 'Les prix varient en fonction des produits. Veuillez consulter notre site pour plus d\'informations.' },
    { keyword: 'salut', response: 'Salut! Comment puis-je vous aider aujourd\'hui?' },
    { keyword: 'ça va', response: 'Oui, merci! Et vous, ça va?' },
    { keyword: 'cava', response: 'Oui, merci! Et vous, ça va?' },
    { keyword: 'ca va', response: 'Oui, merci! Et vous, ça va?' },
    { keyword: 'au revoir', response: 'Au revoir! N\'hésitez pas à revenir si vous avez d\'autres questions.' },
    { keyword: 'merci', response: 'De rien! Je suis là pour vous aider.' },
    { keyword: 'j\'aime', response: 'C\'est super d\'entendre ça! Qu\'est-ce que vous aimez?' },
    { keyword: 'quel temps fait-il', response: 'Désolé, je ne peux pas vérifier la météo, mais vous pouvez consulter un site de météo.' },
    { keyword: 'où se trouve', response: 'Je peux vous aider à trouver cela! De quel endroit parlez-vous?' },
    { keyword: 'quels sont vos produits', response: 'Nous proposons une large gamme de produits: électronique, vêtements, mais aussi des accessoires divers.' },
    { keyword: 'est-ce que vous faites des promotions', response: 'Oui, nous proposons régulièrement des promotions sur notre site. Vérifiez notre section promotions!' },
    { keyword: 'comment passer une commande', response: 'Pour passer une commande, choisissez un produit, ajoutez-le à votre panier, et suivez les étapes de paiement.' },
    { keyword: 'suis-je enregistré', response: 'Si vous avez un compte chez nous, vous êtes enregistré. Vous pouvez vous connecter pour vérifier.' },
    { keyword: 'quoi de neuf', response: 'Nous avons de nouveaux produits et des promotions chaque semaine! Restez à l\'écoute.' },
    { keyword: 'pouvez-vous m\'aider', response: 'Bien sûr! Que puis-je faire pour vous?' },
    { keyword: 'produit électronique', response: 'Nous avons une vaste sélection de produits électroniques, des téléviseurs aux tablettes.' },
    { keyword: 'service après-vente', response: 'Notre service après-vente est là pour vous aider avec tout problème concernant nos produits.' },
    { keyword: 'réduction', response: 'Nous offrons des réductions régulières. Consultez notre site pour les offres actuelles.' },
    { keyword: 'mode de paiement', response: 'Nous acceptons les cartes bancaires, PayPal, et virement bancaire.' },
    { keyword: 'remboursement', response: 'Si vous avez droit à un remboursement, il sera effectué selon notre politique de retour.' },
    { keyword: 'produit en stock', response: 'Tous nos produits disponibles sur le site sont en stock, sauf indication contraire.' },
    { keyword: 'date de livraison', response: 'La date de livraison estimée dépend du mode de livraison choisi, vous serez informé lors de la commande.' },
    { keyword: 'téléphone', response: 'Nous avons plusieurs modèles de téléphones à des prix compétitifs.' },
    { keyword: 'commande annulée', response: 'Si votre commande a été annulée, veuillez vérifier votre email pour plus de détails.' },
    { keyword: 'compte client', response: 'Pour créer un compte client, cliquez sur le bouton "S\'inscrire" dans le coin supérieur droit.' },
    { keyword: 'produit en solde', response: 'Nous proposons des soldes fréquentes. Profitez-en pour obtenir des produits à prix réduits!' },
    { keyword: 'garantie produit', response: 'Tous nos produits sont garantis 2 ans, sauf indication contraire.' },
    { keyword: 'commande', response: 'Pour passer une commande, ajoutez simplement un produit à votre panier et procédez au paiement.' },
    { keyword: 'heure d\'ouverture', response: 'Nous sommes ouverts de 9h à 18h, du lundi au vendredi.' },
    { keyword: 'comment obtenir une facture', response: 'Une fois votre commande terminée, vous recevrez votre facture par email.' },
    { keyword: 'produit en rupture', response: 'Certains produits peuvent être temporairement en rupture de stock. Vous pouvez vous inscrire pour être notifié.' },
    { keyword: 'produits populaires', response: 'Les produits les plus populaires actuellement sont nos téléphones et tablettes.' },
    { keyword: 'produits reconditionnés', response: 'Nous proposons des produits reconditionnés avec une garantie de 1 an.' },
    { keyword: 'réservation', response: 'Vous pouvez réserver des produits via notre site si vous souhaitez les acheter plus tard.' },
    { keyword: 'support technique', response: 'Notre support technique est là pour vous aider avec tous les problèmes techniques que vous rencontrez.' },
    { keyword: 'mode de livraison', response: 'Nous proposons la livraison standard et la livraison express pour toutes les commandes.' },
    { keyword: 'retrait en magasin', response: 'Vous pouvez choisir le retrait en magasin lors de votre commande en ligne.' },
    { keyword: 'avis produit', response: 'Consultez les avis des utilisateurs sur chaque page de produit pour plus de détails.' },
    { keyword: 'choisir un produit', response: 'Pour choisir un produit, consultez notre site et filtrez selon vos préférences.' },
    { keyword: 'remise spéciale', response: 'Nous proposons des remises spéciales lors de nos événements promotionnels.' },
    { keyword: 'offre exclusive', response: 'Abonnez-vous à notre newsletter pour recevoir des offres exclusives et des réductions.' },
    { keyword: 'produits écologiques', response: 'Nous offrons également des produits respectueux de l\'environnement.' },
    { keyword: 'boutique en ligne', response: 'Notre boutique en ligne est disponible 24/7 pour vos achats.' },
    { keyword: 'newsletter', response: 'Abonnez-vous à notre newsletter pour recevoir les dernières promotions et mises à jour.' },
    { keyword: 'réseaux sociaux', response: 'Suivez-nous sur nos réseaux sociaux pour ne rien manquer de nos actualités et promotions.' },
    { keyword: 'évaluation produit', response: 'Nous apprécions vos évaluations de produits, cela nous aide à nous améliorer.' },
    { keyword: 'panier', response: 'Votre panier contient actuellement les produits suivants : [Liste des produits].' },
    { keyword: 'changer adresse', response: 'Vous pouvez changer votre adresse dans les paramètres de votre compte.' },
    { keyword: 'livraison internationale', response: 'Nous proposons la livraison internationale dans plusieurs pays.' },
    { keyword: 'tarifs', response: 'Nos tarifs sont compétitifs et varient selon les produits. Consultez notre site pour les détails.' },
    { keyword: 'salut', response: 'Salut! Comment puis-je vous aider aujourd\'hui?' },
    { keyword: 'merci', response: 'De rien! N\'hésitez pas à me demander si vous avez besoin de quelque chose d\'autre.' },
    { keyword: 'au revoir', response: 'Au revoir! Passez une bonne journée!' },
    { keyword: 'aide', response: 'Bien sûr! Que puis-je faire pour vous?' },
    { keyword: 'bonjour', response: 'Bonjour! Comment puis-je vous assister aujourd\'hui?' },
    { keyword: 'comment ça va', response: 'Je vais bien, merci! Et vous?' },
    { keyword: 'qui es-tu', response: 'Je suis un assistant virtuel ici pour vous aider.' },
    { keyword: 'quoi de neuf', response: 'Pas grand-chose! Et vous?' },
    { keyword: 'j\'ai une question', response: 'Posez votre question! Je suis là pour ça.' },
    { keyword: 'parle-moi de toi', response: 'Je suis un programme conçu pour vous aider avec vos demandes.' },
    { keyword: 'felicitations', response: 'Merci! Que puis-je faire pour célébrer?' },
    { keyword: 'je m\'ennuie', response: 'Que diriez-vous de discuter de vos centres d\'intérêt?' },
    { keyword: 'besoin d\'aide', response: 'Je suis là pour vous! De quoi avez-vous besoin?' },
    { keyword: 'information', response: 'Quel type d\'information recherchez-vous?' },
    { keyword: 'quel temps fait-il', response: 'Je ne peux pas fournir d\'informations en temps réel, mais vous pouvez vérifier la météo sur internet.' },
    { keyword: 'recette', response: 'Quelle recette recherchez-vous? Je peux vous aider!' },
    { keyword: 'musique', response: 'Quels genres de musique aimez-vous?' },
    { keyword: 'films', response: 'Quels films aimez-vous voir?' },
    { keyword: 'livres', response: 'Quels types de livres préférez-vous lire?' },
    { keyword: 'voyage', response: 'Où aimeriez-vous voyager?' },
    { keyword: 'sport', response: 'Quel est votre sport préféré?' },
    { keyword: 'cuisine', response: 'Aimez-vous cuisiner? Quel est votre plat favori?' },
    { keyword: 'animaux', response: 'Avez-vous des animaux de compagnie?' },
    { keyword: 'technologie', response: 'Quels gadgets trouvez-vous les plus intéressants?' },
    { keyword: 'langue', response: 'Quelles langues parlez-vous?' },
    { keyword: 'hobbies', response: 'Quels sont vos passe-temps préférés?' },
    { keyword: 'jeux', response: 'Aimez-vous jouer à des jeux vidéo?' },
    { keyword: 'famille', response: 'Parlez-moi de votre famille.' },
    { keyword: 'travail', response: 'Dans quel domaine travaillez-vous?' },
    { keyword: 'études', response: 'Que faites-vous comme études?' },
    { keyword: 'vacances', response: 'Quels sont vos plans pour les prochaines vacances?' },
    { keyword: 'santé', response: 'Comment prenez-vous soin de votre santé?' },
    { keyword: 'fitness', response: 'Pratiquez-vous un sport ou une activité physique?' },
    { keyword: 'mode', response: 'Quel style préférez-vous en matière de mode?' },
    { keyword: 'art', response: 'Aimez-vous l\'art? Quelle est votre forme d\'art préférée?' },
    { keyword: 'climat', response: 'Que pensez-vous du changement climatique?' },
    { keyword: 'nourriture', response: 'Quelle est votre nourriture préférée?' },
    { keyword: 'culture', response: 'Aimez-vous découvrir d\'autres cultures?' },
    { keyword: 'écrire', response: 'Aimez-vous écrire? Quels genres?' },
    { keyword: 'lecture', response: 'Quel est le dernier livre que vous avez lu?' },
    { keyword: 'photographie', response: 'Êtes-vous passionné par la photographie?' },
    { keyword: 'nature', response: 'Aimez-vous passer du temps en nature?' },
    { keyword: 'séries', response: 'Quelles séries suivez-vous en ce moment?' },
    { keyword: 'mode de vie', response: 'Quel type de mode de vie aspirez-vous?' },
    { keyword: 'témoignages', response: 'Avez-vous une histoire inspirante à partager?' },
    { keyword: 'globe-trotter', response: 'Quel est le pays que vous rêvez de visiter?' },
    { keyword: 'musées', response: 'Quel est votre musée préféré?' },
    { keyword: 'fête', response: 'Comment célébrez-vous votre anniversaire?' },
    { keyword: 'tech', response: 'Quelle est la dernière innovation technologique qui vous a impressionné?' },
    { keyword: 'histoire', response: 'Quel est votre événement historique préféré?' },
    { keyword: 'philosophie', response: 'Quel est votre concept philosophique préféré?' },
    { keyword: 'voyage spirituel', response: 'Avez-vous déjà fait un voyage spirituel?' },
    { keyword: 'croyance', response: 'Parlez-moi de vos croyances.' },
    { keyword: 'méditation', response: 'Pratiquez-vous la méditation?' },
    { keyword: 'apprentissage', response: 'Qu\'aimez-vous apprendre?' },
    { keyword: 'volontariat', response: 'Avez-vous déjà fait du bénévolat?' },
    { keyword: 'communication', response: 'Que pensez-vous de l\'importance de la communication?' },
    { keyword: 'leadership', response: 'Quels traits valorisez-vous dans un leader?' },
    { keyword: 'innovation', response: 'Quelle est selon vous l\'innovation la plus marquante?' },
    { keyword: 'intelligence émotionnelle', response: 'Que pensez-vous de l\'intelligence émotionnelle?' },
    { keyword: 'entraide', response: 'Aimez-vous aider les autres?' },
    { keyword: 'succès', response: 'Comment définissez-vous le succès?' },
    { keyword: 'échec', response: 'Que pensez-vous de l\'échec?' },
    { keyword: 'éducation', response: 'Quelle est votre opinion sur le système éducatif?' },
    { keyword: 'carrière', response: 'Quels sont vos objectifs de carrière?' },
    { keyword: 'partage', response: 'Aimez-vous partager vos expériences?' },
    { keyword: 'pensée critique', response: 'Que signifie pour vous la pensée critique?' },
    { keyword: 'entrepreneuriat', response: 'Avez-vous déjà pensé à créer votre propre entreprise?' },
    { keyword: 'réseautage', response: 'Quelle importance accordez-vous au réseautage?' },
    { keyword: 'équilibre', response: 'Comment trouvez-vous l\'équilibre entre vie professionnelle et personnelle?' },
    { keyword: 'écologie', response: 'Que pensez-vous de l\'écologie?' },
    { keyword: 'bien-être', response: 'Comment prenez-vous soin de votre bien-être?' },
    { keyword: 'confiance', response: 'Que signifie la confiance pour vous?' },
    { keyword: 'respect', response: 'Pourquoi le respect est-il important selon vous?' },
    { keyword: 'tolerance', response: 'Que signifie la tolérance pour vous?' },
    { keyword: 'inspiration', response: 'Qu\'est-ce qui vous inspire le plus?' },
    { keyword: 'persévérance', response: 'Comment définissez-vous la persévérance?' },
    { keyword: 'créativité', response: 'Êtes-vous créatif? Comment l\'exprimez-vous?' },
    { keyword: 'auto-discipline', response: 'Comment travaillez-vous sur votre auto-discipline?' },
    { keyword: 'réflexion', response: 'Aimez-vous prendre du temps pour réfléchir?' },
    { keyword: 'voyage intérieur', response: 'Qu\'est-ce que cela signifie pour vous?' },
    { keyword: 'égalité', response: 'Que signifie l\'égalité pour vous?' },
    { keyword: 'justice', response: 'Pourquoi la justice est-elle importante?' },
    { keyword: 'engagement', response: 'Êtes-vous engagé dans une cause?' },
    { keyword: 'cultures', response: 'Aimez-vous découvrir différentes cultures?' },
    { keyword: 'partenariat', response: 'Quelle est l\'importance d\'un bon partenariat?' },
    { keyword: 'communauté', response: 'Que signifie la communauté pour vous?' },
    { keyword: 'connection', response: 'Comment établissez-vous des connexions significatives?' },
    { keyword: 'resilience', response: 'Avez-vous des exemples de résilience dans votre vie?' },
    { keyword: 'adaptabilité', response: 'Comment gérez-vous le changement?' },
    { keyword: 'optimisme', response: 'Êtes-vous optimiste de nature?' },
    { keyword: 'pessimisme', response: 'Comment le pessimisme affecte-t-il votre vie?' },
    { keyword: 'curiosité', response: 'Qu\'est-ce qui vous rend curieux?' },
    { keyword: 'exploration', response: 'Aimez-vous explorer de nouvelles idées?' },
    { keyword: 'passion', response: 'Quelle est votre passion dans la vie?' },
    { keyword: 'engagement social', response: 'Participez-vous à des initiatives d\'engagement social?' },
    { keyword: 'encouragement', response: 'Comment encouragez-vous les autres?' },
    { keyword: 'reconnaissance', response: 'Que signifie la reconnaissance pour vous?' },
    { keyword: 'positivité', response: 'Comment cultivez-vous la positivité?' },
    { keyword: 'compassion', response: 'Pourquoi la compassion est-elle importante?' },
    { keyword: 'lien', response: 'Comment établissez-vous des liens avec les autres?' },
    { keyword: 'image de soi', response: 'Comment percevez-vous votre image de soi?' },
    { keyword: 'authenticité', response: 'Que signifie être authentique pour vous?' },
    { keyword: 'contribution', response: 'Comment contribuez-vous à votre communauté?' },
    { keyword: 'réussite', response: 'Qu\'est-ce qui représente la réussite pour vous?' },
    { keyword: 'culture d\'entreprise', response: 'Quelle est l\'importance de la culture d\'entreprise?' },
    { keyword: 'travail d\'équipe', response: 'Pourquoi le travail d\'équipe est-il essentiel?' },
    { keyword: 'décision', response: 'Comment prenez-vous des décisions?' },
    { keyword: 'valeurs', response: 'Quelles sont vos valeurs personnelles?' },
    { keyword: 'vision', response: 'Quelle est votre vision pour l\'avenir?' },
    { keyword: 'sensibilité', response: 'Pourquoi la sensibilité est-elle importante dans les relations?' },
    { keyword: 'amicaux', response: 'Quels traits recherchez-vous chez un ami?' },
    { keyword: 'honnêteté', response: 'À quel point l\'honnêteté est-elle essentielle pour vous?' },
    { keyword: 'empathie', response: 'Que signifie l\'empathie pour vous?' },
    { keyword: 'perspective', response: 'Quelle est votre perspective sur la vie?' },
    { keyword: 'altruisme', response: 'Croyez-vous en l\'altruisme?' },
    { keyword: 'développement personnel', response: 'Comment travaillez-vous sur votre développement personnel?' },
    { keyword: 'réflexion personnelle', response: 'Prenez-vous du temps pour la réflexion personnelle?' },
    { keyword: 'réussite personnelle', response: 'Que signifie la réussite personnelle pour vous?' },
    { keyword: 'ambition', response: 'Quelle est votre plus grande ambition?' },
    { keyword: 'pardon', response: 'Que pensez-vous du pardon?' },
    { keyword: 'réconciliation', response: 'Comment procédez-vous à une réconciliation?' },
    { keyword: 'adaptation', response: 'Comment vous adaptez-vous à des situations nouvelles?' },
    { keyword: 'écoute active', response: 'Quelle est l\'importance de l\'écoute active selon vous?' },
    { keyword: 'acceptation', response: 'Que signifie l\'acceptation pour vous?' },
    { keyword: 'satisfaction', response: 'Qu\'est-ce qui vous apporte de la satisfaction?' },
    { keyword: 'respect de soi', response: 'Comment développez-vous votre respect de soi?' },
    { keyword: 'confiance en soi', response: 'Comment renforcez-vous votre confiance en vous?' },
    { keyword: 'évolution', response: 'Comment voyez-vous votre évolution personnelle?' },
    { keyword: 'compliments', response: 'Aimez-vous faire ou recevoir des compliments?' },
    { keyword: 'gratitude', response: 'Pour quoi êtes-vous reconnaissant aujourd\'hui?' },
    { keyword: 'partages d\'expériences', response: 'Quelles expériences aimez-vous partager?' },
    { keyword: 'modes de vie', response: 'Quel mode de vie vous attire le plus?' },
    { keyword: 'enseignements', response: 'Quelles leçons avez-vous apprises dans la vie?' },
    { keyword: 'partage de connaissances', response: 'Aimez-vous partager vos connaissances avec les autres?' },
    { keyword: 'réflexion sur les relations', response: 'Comment procédez-vous à la réflexion sur vos relations?' },
    { keyword: 'développement de carrière', response: 'Comment envisagez-vous votre développement de carrière?' },
    { keyword: 'maturité', response: 'Que signifie la maturité pour vous?' },
    { keyword: 'thérapie', response: 'Que pensez-vous des thérapies?' },
    { keyword: 'soutien', response: 'Comment apportez-vous du soutien aux autres?' },
    { keyword: 'connexion humaine', response: 'Pourquoi la connexion humaine est-elle importante?' },
    { keyword: 'communication ouverte', response: 'Quelle est l\'importance de la communication ouverte?' },
    { keyword: 'influence', response: 'Qui vous influence le plus dans la vie?' },
    { keyword: 'potentiel', response: 'Comment réalisez-vous votre potentiel?' },
    { keyword: 'inspiration', response: 'D\'où tirez-vous votre inspiration?' },
    { keyword: 'échange d\'idées', response: 'Quel est l\'impact de l\'échange d\'idées sur vous?' },
    { keyword: 'collaboration', response: 'Qu\'est-ce qui rend la collaboration efficace?' },
    { keyword: 'l\'impact des réseaux sociaux', response: 'Quel impact les réseaux sociaux ont-ils sur votre vie?' },
    { keyword: 'sens des responsabilités', response: 'Que signifie le sens des responsabilités pour vous?' },
    { keyword: 'pratiques de bien-être', response: 'Quelles pratiques de bien-être suivez-vous?' },
    { keyword: 'culture de la paix', response: 'Pourquoi la culture de la paix est-elle essentielle?' },
    { keyword: 'responsabilité sociale', response: 'Que signifie la responsabilité sociale pour vous?' },
    { keyword: 'capacité d\'écoute', response: 'Quelle importance accordez-vous à la capacité d\'écoute?' },
    { keyword: 'éthique', response: 'Que pensez-vous de l\'éthique dans les affaires?' },
    { keyword: 'spiritualité', response: 'Quelle importance accordez-vous à votre spiritualité?' },
    { keyword: 'identité personnelle', response: 'Comment définissez-vous votre identité personnelle?' },
    { keyword: 'mentalité de croissance', response: 'Avez-vous une mentalité de croissance?' },
    { keyword: 'savoir-être', response: 'Que signifie le savoir-être pour vous?' },
    { keyword: 'perspective de vie', response: 'Quelle est votre perspective de la vie?' },
    { keyword: 'détermination', response: 'Comment faites-vous preuve de détermination dans vos objectifs?' },
    { keyword: 'état d\'esprit positif', response: 'Comment cultivez-vous un état d\'esprit positif?' },
    { keyword: 'gestion du temps', response: 'Comment gérez-vous votre temps efficacement?' },
    { keyword: 'gratification instantanée', response: 'Quelle est votre opinion sur la gratification instantanée?' },
    { keyword: 'vision à long terme', response: 'Quelle est votre vision à long terme pour votre vie?' },
    { keyword: 'découverte de soi', response: 'Comment faites-vous pour découvrir qui vous êtes vraiment?' },
    { keyword: 'face aux défis', response: 'Comment faites-vous face aux défis?' },
    { keyword: 'accomplissements', response: 'De quoi êtes-vous le plus fier dans votre vie?' },
    { keyword: 'priorités', response: 'Quelles sont vos priorités dans la vie?' },
    { keyword: 'transitions', response: 'Comment gérez-vous les transitions dans votre vie?' },
    { keyword: 'vision communautaire', response: 'Quelle est votre vision pour votre communauté?' },
    { keyword: 'impact positif', response: 'Comment générez-vous un impact positif dans la vie des autres?' },
    { keyword: 'négociation', response: 'Comment abordez-vous les négociations?' },
    { keyword: 'débat', response: 'Que pensez-vous des débats d\'idées?' },
    { keyword: 'contributions', response: 'Comment vos contributions peuvent-elles influencer le monde?' },
    { keyword: 'histoire peut bien changer', response: 'Quelle histoire pouvez-vous partager qui pourrait changer les choses?' },
    { keyword: 'lien intergénérationnel', response: 'Comment renforcez-vous les liens intergénérationnels?' },
    { keyword: 'transmission des savoirs', response: 'Pourquoi la transmission des savoirs est-elle cruciale?' },
    { keyword: 'unité', response: 'Quelle importance accordez-vous à l\'unité?' },
    { keyword: 'façon de penser', response: 'Comment votre façon de penser a-t-elle évolué?' },
    { keyword: 'vivre pleinement', response: 'Que signifie vivre pleinement pour vous?' },
    { keyword: 'capacité d\'adaptation', response: 'Comment démontrez-vous votre capacité d\'adaptation?' },
    { keyword: 'développement durable', response: 'Comment contribuez-vous au développement durable?' },
    { keyword: 'innovation sociale', response: 'Que pensez-vous de l\'innovation sociale?' },
    { keyword: 'partage de ressources', response: 'Pourquoi le partage de ressources est important?' },
    { keyword: 'réciprocité', response: 'Que signifie la réciprocité pour vous?' },
    { keyword: 'surmonter des obstacles', response: 'Comment surmontez-vous les obstacles?' },
    { keyword: 'travail sur soi', response: 'Comment travaillez-vous sur vous-même?' },
    { keyword: 'écoute empathique', response: 'Que signifie l\'écoute empathique pour vous?' },
    { keyword: 'valeur des relations', response: 'Quelle est la valeur des relations dans votre vie?' },
    { keyword: 'résolution de conflits', response: 'Comment gérez-vous la résolution de conflits?' },
    { keyword: 'épicentre des changements', response: 'Que représente l\'épicentre des changements pour vous?' },
    { keyword: 'financement participatif', response: 'Que pensez-vous du financement participatif?' },
    { keyword: 'connexion au monde', response: 'Comment vous connectez-vous au monde qui vous entoure?' },
    { keyword: 'partenariats', response: 'Quelle est l\'importance des partenariats?' },
    { keyword: 'voix collective', response: 'Que signifie avoir une voix collective?' },
    { keyword: 'pouvoir d\'agir', response: 'Comment exercez-vous votre pouvoir d\'agir?' },
    { keyword: 'défis et opportunités', response: 'Comment percevez-vous les défis et les opportunités?' },
    { keyword: 'changement de mentalité', response: 'Comment un changement de mentalité peut-il influencer un individu?' },
    { keyword: 'écologie', response: 'Que faites-vous pour l\'écologie?' },
    { keyword: 'pouvoir de la créativité', response: 'Comment la créativité peut-elle changer les choses?' },
    { keyword: 'biens communs', response: 'Que signifie les biens communs pour vous?' },
    { keyword: 'rôle actif', response: 'Quel rôle jouez-vous dans votre communauté?' },
    { keyword: 'micro-changements', response: 'Comment les micro-changements peuvent-ils avoir un grand impact?' },
    { keyword: 'transcendance', response: 'Que signifie la transcendance pour vous?' },
    { keyword: 'enquête de satisfaction', response: 'Participez-vous à des enquêtes de satisfaction?' },
    { keyword: 'plaidoyer', response: 'Avez-vous déjà plaidé pour une cause?' },
    { keyword: 'réalités locales', response: 'Comment gérez-vous les réalités locales où vous vivez?' },
    { keyword: 'équilibre entre vie professionnelle et personnelle', response: 'Comment parvenez-vous à équilibrer vie professionnelle et personnelle?' },
    { keyword: 'innovations écologiques', response: 'Que pensez-vous des innovations écologiques?' },
    { keyword: 'humilité', response: 'Quelle importance accordez-vous à l\'humilité?' },
    { keyword: 'endurance', response: 'Comment testez-vous votre endurance dans la vie?' },
    { keyword: 'travaillons ensemble', response: 'Comment pouvons-nous travailler ensemble efficacement?' },
    { keyword: 'pratiques de justice sociale', response: 'Que signifie pour vous la justice sociale?' },
    { keyword: 'solidarité', response: 'Quelle est l\'importance de la solidarité dans notre société?' },
    { keyword: 'exploration des possibilités', response: 'Comment explorez-vous les possibilités dans votre vie?' },
    { keyword: 'impact communautaire', response: 'Quelles actions ont le plus d\'impact sur votre communauté?' },
    { keyword: 'salut', response: 'Salut! Comment puis-je vous aider aujourd\'hui?' },
    { keyword: 'bonjour', response: 'Bonjour! Comment puis-je vous aider?' },
    { keyword: 'bonsoir', response: 'Bonsoir! Comment puis-je vous aider?' },
    { keyword: 'cava', response: 'Oui, merci! Et vous, ça va?' },
    { keyword: 'ca va', response: 'Oui, merci! Et vous, ça va?' },
    { keyword: 'comment ca va', response: 'Oui, merci! Et vous, ça va?' },
    { keyword: 'ca vas', response: 'Oui, merci! Et vous, ça va?' },
    { keyword: 'ça va', response: 'Oui, merci! Et vous, ça va?' },
    { keyword: 'comment ça va', response: 'Oui, merci! Et vous, ça va?' },
    { keyword: 'ça vas', response: 'Oui, merci! Et vous, ça va?' },
    { keyword: 'ça va bien', response: 'Oui, merci! Et vous, ça va bien?' },
    { keyword: 'comment vas-tu', response: 'Je vais bien, merci! Et toi, comment vas-tu?' },
    { keyword: 'comment vas', response: 'Je vais bien, merci! Et toi, comment vas-tu?' },
    { keyword: 'ça roule', response: 'Oui, ça roule! Et toi?' },
    { keyword: 'salut comment ça va', response: 'Salut! Ça va bien, et toi?' },
    { keyword: 'salut ça va', response: 'Salut! Ça va bien, et toi?' },
    { keyword: 'yo', response: 'Yo! Comment ça va?' },
    { keyword: 'wesh', response: 'Wesh! Comment ça va?' },
    { keyword: 'ca roule', response: 'Oui, ça roule! Et toi?' },
    { keyword: 'comment ça roule', response: 'Ça roule bien, et toi?' },
    { keyword: 'slt', response: 'Salut! Comment ça va?' },
    { keyword: 'salut toi', response: 'Salut! Comment puis-je t\'aider?' },
    { keyword: 'bonjour à tous', response: 'Bonjour! Comment puis-je vous aider?' },
    { keyword: 'salut tout le monde', response: 'Salut! Comment puis-je vous aider?' },
    { keyword: 'salut tout', response: 'Salut! Comment ça va?' },
    { keyword: 'quoi de neuf', response: 'Rien de neuf! Et toi?' },
    { keyword: 'ca va et toi', response: 'Oui, ça va bien! Et toi?' },
    { keyword: 'ca va bien et toi', response: 'Oui, ça va bien! Et toi?' },
    { keyword: 'comment tu vas', response: 'Je vais bien, merci! Et toi?' },
    { keyword: 'tout va bien', response: 'Tout va bien, merci! Et toi?' },
    { keyword: 'comment ca roule', response: 'Ça roule! Et toi?' },
    { keyword: 'quoi de neuf', response: 'Rien de neuf! Et toi?' },
    { keyword: 'bienvenue', response: 'Merci! Comment puis-je vous aider?' },
    { keyword: 'salut ça va bien', response: 'Salut! Ça va bien, et toi?' },
    { keyword: 'ça va très bien', response: 'Je vais très bien, merci! Et toi?' },
    { keyword: 'ça va bien et toi', response: 'Oui, ça va bien, et toi?' },
    { keyword: 'salut mon ami', response: 'Salut! Comment ça va?' },
    { keyword: 'ça va tranquille', response: 'Oui, ça va tranquille! Et toi?' },
    { keyword: 'salut toi même', response: 'Salut! Comment ça va?' },
    { keyword: 'ça va super', response: 'Ça va super! Et toi?' },
    { keyword: 'salut tout le monde', response: 'Salut! Comment puis-je vous aider?' },
    { keyword: 'ça va bien merci', response: 'Je vais bien, merci! Et toi?' },
    { keyword: 'salut salut', response: 'Salut! Comment ça va?' },
    { keyword: 'comment tu te sens', response: 'Je me sens bien, merci! Et toi?' },
    { keyword: 'ça va fort', response: 'Ça va fort! Et toi?' },
    { keyword: 'ça va mieux', response: 'Ça va mieux, merci! Et toi?' },
    { keyword: 'comment se passe la journée', response: 'La journée se passe bien! Et toi?' },
    { keyword: 'ça fait longtemps', response: 'Oui, ça fait longtemps! Comment ça va?' },
    { keyword: 'tout roule', response: 'Tout roule! Et toi?' },
    { keyword: 'salut mon pote', response: 'Salut! Comment ça va?' },
    { keyword: 'ça va très bien', response: 'Ça va très bien! Et toi?' },
    { keyword: 'ça roule tranquille', response: 'Ça roule tranquille! Et toi?' },
    { keyword: 'ça va fort', response: 'Ça va fort! Et toi?' },
    { keyword: 'coucou', response: 'Coucou! Comment ça va?' },
    { keyword: 'salut comment vas-tu', response: 'Salut! Ça va bien, et toi?' },
    { keyword: 'bonsoir à toi', response: 'Bonsoir! Comment puis-je t\'aider?' },
    { keyword: 'salut comment va', response: 'Salut! Comment va ta journée?' },
    { keyword: 'slt ca va', response: 'Salut! Ça va bien, et toi?' },
    { keyword: 'ça va tranquille', response: 'Ça va tranquille! Et toi?' },
    { keyword: 'salut ma couille', response: 'Salut! Comment ça va?' },
    { keyword: 'ca va bien', response: 'Ça va bien, merci! Et toi?' },
    { keyword: 'ça va moyen', response: 'Désolé d\'entendre ça. Est-ce que je peux t\'aider?' },
    { keyword: 'ça va pas mal', response: 'Ça va pas mal, merci! Et toi?' },
    { keyword: 'salut mon gars', response: 'Salut! Comment ça va?' },
    { keyword: 'ça va bien et toi', response: 'Oui, ça va bien, et toi?' },
    { keyword: 'bien joué', response: 'Merci! Comment puis-je vous aider?' },
    { keyword: 'comment va la vie', response: 'La vie va bien! Et toi?' },
    { keyword: 'ça va comme sur des roulettes', response: 'Oui, ça va très bien! Et toi?' },
    { keyword: 'ca va à merveille', response: 'Ça va à merveille! Et toi?' },
    { keyword: 'comment tu vas bien', response: 'Je vais bien, merci! Et toi?' },
    { keyword: 'salut tout va bien', response: 'Salut! Ça va bien, et toi?' },
    { keyword: 'ça va tranquille', response: 'Ça va tranquille, merci! Et toi?' },
    { keyword: 'hello', response: 'Hello! How can I help you today?' },
    { keyword: 'hello there', response: 'Hello! How can I assist you?' },
    { keyword: 'hi', response: 'Hi! How can I help you today?' },
    { keyword: 'hey', response: 'Hey! How can I assist you?' },
    { keyword: 'salut ca roule', response: 'Oui, ça roule! Et toi?' },
    { keyword: 'salut tout le monde', response: 'Salut! Comment puis-je vous aider?' },
    { keyword: 'salut ca va bien', response: 'Salut! Ça va bien, et toi?' },
    { keyword: 'comment ca va aujourd\'hui', response: 'Ça va bien! Et toi, comment ça va?' },
    { keyword: 'salut ca va fort', response: 'Salut! Ça va fort, et toi?' },
    { keyword: 'ça va pas trop mal', response: 'Ça va pas trop mal, merci! Et toi?' },
    { keyword: 'salut ca va super bien', response: 'Salut! Ça va super bien, et toi?' },
    { keyword: 'salut tout va bien', response: 'Salut! Ça va bien, et toi?' },
    { keyword: 'bien joué', response: 'Merci! Comment puis-je vous aider?' },
{ keyword: 'service', response: 'Quel type de service recherchez-vous? Je suis là pour vous aider!' },
{ keyword: 'où est la boutique', response: 'La boutique est uniquement en ligne pour l\'instant.' },
{ keyword: 'horaires', response: 'Nos horaires sont disponibles en ligne, vous pouvez consulter notre site pour plus de détails.' },
{ keyword: 'comment acheter', response: 'Pour acheter, vous pouvez naviguer sur notre site et ajouter les articles à votre panier.' },
{ keyword: 'produits en stock', response: 'Tous nos produits sont mis à jour régulièrement sur notre site.' },
{ keyword: 'livraison', response: 'Nous offrons une livraison standard et express. Vous pouvez choisir l\'option lors de la commande.' },
{ keyword: 'retours', response: 'Vous pouvez demander un retour sous 30 jours après l\'achat si l\'article est dans son état d\'origine.' },
{ keyword: 'paiement sécurisé', response: 'Nous utilisons des méthodes de paiement sécurisées comme PayPal et cartes bancaires.' },
{ keyword: 'compte client', response: 'Vous pouvez créer un compte sur notre site pour suivre vos commandes et recevoir des offres spéciales.' },
{ keyword: 'panier', response: 'Vous pouvez consulter votre panier en cliquant sur l\'icône en haut à droite de notre site.' },
{ keyword: 'prix', response: 'Les prix de nos produits sont affichés directement sur notre site lors de la consultation des articles.' },
{ keyword: 'disponibilité', response: 'La disponibilité des produits est indiquée sur la page de chaque article.' },
{ keyword: 'offres spéciales', response: 'Nous proposons régulièrement des promotions et des offres spéciales. Restez connecté!' },
{ keyword: 'nouveautés', response: 'Les nouveaux produits sont affichés sur notre page d\'accueil et dans la section nouveautés.' },
{ keyword: 'vêtements', response: 'Nos vêtements sont disponibles dans plusieurs tailles et couleurs. Consultez notre section mode pour plus de détails.' },
{ keyword: 'accessoires', response: 'Nous avons une large gamme d\'accessoires disponibles dans notre boutique en ligne.' },
{ keyword: 'chaussures', response: 'Nos chaussures sont disponibles pour tous les styles et occasions. Découvrez-les dans notre catégorie chaussures.' },
{ keyword: 'fournisseurs', response: 'Nous travaillons avec des fournisseurs de confiance pour vous offrir les meilleurs produits.' },
{ keyword: 'stock', response: 'Nous mettons régulièrement à jour nos stocks. Consultez notre site pour voir les articles disponibles.' },
{ keyword: 'garantie', response: 'Tous nos produits bénéficient d\'une garantie de 2 ans, selon les conditions indiquées sur notre site.' },
{ keyword: 'réduction', response: 'Les réductions sont appliquées automatiquement au moment de la commande si des offres sont disponibles.' },
{ keyword: 'support', response: 'Si vous avez des questions, n\'hésitez pas à contacter notre équipe de support via le chat ou le formulaire de contact.' },
{ keyword: 'contact', response: 'Vous pouvez nous contacter via le formulaire de notre site ou par email à support@notresite.com.' },
{ keyword: 'avis', response: 'Nous apprécions vos avis! Laissez un commentaire sur nos produits après votre achat.' },
{ keyword: 'produit défectueux', response: 'Si votre produit est défectueux, contactez-nous dans les 30 jours suivant l\'achat pour obtenir un échange ou un remboursement.' },
{ keyword: 'retard de livraison', response: 'Si vous avez un retard de livraison, contactez-nous pour que nous puissions résoudre le problème.' },
{ keyword: 'commande', response: 'Vous pouvez suivre l\'état de votre commande directement depuis votre compte client.' },
{ keyword: 'réservation', response: 'Pour réserver un produit, ajoutez-le à votre panier et procédez à la commande.' },
{ keyword: 'compte', response: 'Créez un compte pour faciliter vos futurs achats et profiter d\'offres exclusives.' },
{ keyword: 'newsletter', response: 'Abonnez-vous à notre newsletter pour recevoir des offres et des nouveautés directement dans votre boîte mail.' },
{ keyword: 'coupon', response: 'Entrez le code promo dans votre panier pour bénéficier de réductions sur votre commande.' },
{ keyword: 'produit personnalisé', response: 'Nous proposons des produits personnalisés. Consultez la section personnalisation pour plus d\'informations.' },
{ keyword: 'produit épuisé', response: 'Si un produit est épuisé, vous pouvez vous inscrire pour recevoir une notification dès qu\'il sera de nouveau disponible.' },
{ keyword: 'produit exclusif', response: 'Découvrez nos produits exclusifs, disponibles uniquement sur notre site en ligne.' },
{ keyword: 'sécurité', response: 'Nous utilisons des protocoles de sécurité avancés pour protéger vos informations personnelles et bancaires.' },
{ keyword: 'détails de la commande', response: 'Vous pouvez voir les détails de votre commande dans l\'historique de votre compte.' },
{ keyword: 'services supplémentaires', response: 'Nous proposons divers services supplémentaires, comme l\'emballage cadeau et la gravure.' },
{ keyword: 'satisfaction', response: 'Votre satisfaction est notre priorité. Contactez-nous si vous n\'êtes pas satisfait de votre achat.' },
{ keyword: 'réclamation', response: 'Pour toute réclamation, veuillez nous envoyer un message via le formulaire de contact sur notre site.' },
{ keyword: 'annulation', response: 'Les commandes peuvent être annulées dans un délai de 24 heures après l\'achat.' },
{ keyword: 'réexpédition', response: 'Si un article est retourné, nous pouvons organiser une réexpédition selon vos préférences.' },
{ keyword: 'points de fidélité', response: 'Vous pouvez accumuler des points de fidélité à chaque achat, échangeables contre des réductions sur vos prochaines commandes.' },
{ keyword: 'catalogue', response: 'Consultez notre catalogue en ligne pour voir tous nos produits et leurs descriptions détaillées.' },
{ keyword: 'recherche', response: 'Utilisez notre barre de recherche pour trouver rapidement le produit que vous cherchez.' },
{ keyword: 'commentaires', response: 'Laissez un commentaire pour partager votre expérience avec nos produits et services.' },
{ keyword: 'seulement en ligne', response: 'Tous nos produits sont disponibles uniquement en ligne pour le moment.' },
{ keyword: 'livraison gratuite', response: 'Nous offrons la livraison gratuite sur toutes les commandes supérieures à 50€.' },
{ keyword: 'méthodes de paiement', response: 'Nous acceptons les paiements par carte bancaire, PayPal et autres méthodes sécurisées.' },
{ keyword: 'produits populaires', response: 'Consultez notre section des produits populaires pour découvrir les articles les plus vendus.' },
{ keyword: 'offre limitée', response: 'Cette offre est limitée, alors ne manquez pas votre chance de profiter de réductions exceptionnelles!' },
{ keyword: 'cadeaux', response: 'Découvrez notre sélection de cadeaux pour toutes les occasions.' },
{ keyword: 'emballage cadeau', response: 'Vous pouvez choisir l\'option emballage cadeau lors de votre commande.' },
{ keyword: 'produits écologiques', response: 'Nous proposons une gamme de produits écologiques et respectueux de l\'environnement.' },
{ keyword: 'réduction d\'impôt', response: 'Certains produits sont éligibles à une réduction d\'impôt, consultez notre site pour plus de détails.' },
{ keyword: 'réservation en ligne', response: 'Réservez en ligne pour garantir votre place et bénéficier de tarifs exclusifs.' },
{ keyword: 'produit en précommande', response: 'Les produits en précommande seront expédiés dès qu\'ils seront disponibles.' },
{ keyword: 'recommandations', response: 'En fonction de vos achats précédents, nous vous recommandons ces produits.' },
{ keyword: 'échange', response: 'Si vous souhaitez échanger un produit, contactez-nous pour connaître les conditions d\'échange.' },
{ keyword: 'assistance', response: 'Notre équipe d\'assistance est disponible 24/7 pour répondre à vos questions.' },
{ keyword: 'calcul frais de port', response: 'Les frais de port sont calculés automatiquement lors du passage en caisse, selon votre localisation.' },
{ keyword: 'virement bancaire', response: 'Vous pouvez également choisir de payer par virement bancaire. Les informations nécessaires vous seront envoyées après la commande.' },
{ keyword: 'carte cadeau', response: 'Offrez une carte cadeau pour permettre à vos proches de choisir leurs produits préférés.' },
{ keyword: 'article en solde', response: 'Consultez notre section des soldes pour profiter des meilleures offres.' },
{ keyword: 'promotions', response: 'Restez à l\'affût des promotions en cours sur notre site pour des réductions exceptionnelles.' },
{ keyword: 'sélection de produits', response: 'Découvrez notre sélection de produits tendance dans chaque catégorie.' },
{ keyword: 'réduction étudiants', response: 'Les étudiants bénéficient d\'une réduction spéciale sur présentation de leur carte étudiant.' },
{ keyword: 'retrait en magasin', response: 'Nous proposons un service de retrait en magasin pour les commandes en ligne.' },
{ keyword: 'mode', response: 'Découvrez notre collection de mode actuelle, avec des vêtements adaptés à toutes les saisons.' },
{ keyword: 'produits électroniques', response: 'Nos produits électroniques sont testés pour garantir leur performance et leur fiabilité.' },
{ keyword: 'offre anniversaire', response: 'Recevez une offre spéciale pour votre anniversaire en vous inscrivant à notre newsletter.' },
{ keyword: 'page d\'accueil', response: 'Retournez à notre page d\'accueil pour découvrir toutes les nouveautés et promotions.' },
{ keyword: 'politique de confidentialité', response: 'Vous pouvez consulter notre politique de confidentialité pour en savoir plus sur la gestion de vos données.' },
{ keyword: 'frais supplémentaires', response: 'Les frais supplémentaires peuvent s\'appliquer en fonction de la méthode de paiement choisie.' },
{ keyword: 'produits locaux', response: 'Nous soutenons les producteurs locaux en proposant des produits fabriqués en Tunisie.' },
{ keyword: 'produits artisanaux', response: 'Nous proposons une gamme de produits artisanaux faits à la main, parfaits pour un cadeau unique.' },
{ keyword: 'programme de fidélité', response: 'Rejoignez notre programme de fidélité pour obtenir des réductions et des offres spéciales.' },
{ keyword: 'système de notation', response: 'Notez vos produits préférés et aidez les autres clients à faire leur choix.' },
{ keyword: 'garantie prolongée', response: 'Prolongez la garantie de vos produits pour bénéficier d\'une couverture supplémentaire.' },
{ keyword: 'produits haut de gamme', response: 'Découvrez notre sélection de produits haut de gamme, pour des articles de qualité supérieure.' },
{ keyword: 'produits de luxe', response: 'Nous avons une collection de produits de luxe, parfaits pour un cadeau raffiné.' },
{ keyword: 'satisfaction client', response: 'Votre satisfaction est notre priorité, contactez-nous si vous avez des préoccupations.' },
{ keyword: 'test produit', response: 'Nous réalisons des tests rigoureux sur nos produits pour garantir leur qualité avant la mise en vente.' },
{ keyword: 'évaluation', response: 'Évaluez vos achats et laissez des commentaires pour aider les autres clients.' },
{ keyword: 'commande', response: 'Votre commande a bien été enregistrée.' },
{ keyword: 'produit', response: 'Le produit est en stock et prêt à être expédié.' },
{ keyword: 'paiement', response: 'Le paiement a été effectué avec succès.' },
{ keyword: 'livraison', response: 'La livraison est en cours et devrait arriver sous peu.' },
{ keyword: 'panier', response: 'Votre panier est actuellement vide.' },
{ keyword: 'offre', response: 'Profitez de notre offre spéciale avant qu\'elle n\'expire.' },
{ keyword: 'prix', response: 'Le prix du produit est affiché sur la page de chaque article.' },
{ keyword: 'réduction', response: 'Vous bénéficiez d\'une réduction de 20 % sur ce produit.' },
{ keyword: 'retour', response: 'Les retours sont acceptés dans les 30 jours suivant la réception.' },
{ keyword: 'remboursement', response: 'Votre remboursement sera traité dans un délai de 5 jours.' },
{ keyword: 'service', response: 'Notre service client est disponible pour répondre à vos questions.' },
{ keyword: 'contact', response: 'N\'hésitez pas à nous contacter si vous avez des questions.' },
{ keyword: 'disponibilité', response: 'Le produit est actuellement disponible en stock.' },
{ keyword: 'magasin', response: 'Le magasin est ouvert de 9h à 18h du lundi au vendredi.' },
{ keyword: 'carte', response: 'Vous pouvez payer avec votre carte bancaire.' },
{ keyword: 'abonnement', response: 'L\'abonnement à notre newsletter vous permet de recevoir des offres exclusives.' },
{ keyword: 'produits', response: 'Nous avons une large gamme de produits disponibles en ligne.' },
{ keyword: 'livraison gratuite', response: 'La livraison gratuite est disponible pour toute commande supérieure à 50 €.' },
{ keyword: 'client', response: 'Nous vous remercions de votre fidélité en tant que client.' },
{ keyword: 'bénéfice', response: 'Profitez des avantages réservés aux membres du programme de fidélité.' },
{ keyword: 'offre limitée', response: 'Cette offre est limitée, ne la manquez pas!' },
{ keyword: 'assistance', response: 'Notre équipe d\'assistance est là pour vous aider en cas de besoin.' },
{ keyword: 'produit écologique', response: 'Nous proposons des produits écologiques et respectueux de l\'environnement.' },
{ keyword: 'échange', response: 'Les échanges de produits sont possibles dans un délai de 30 jours.' },
{ keyword: 'remise', response: 'Obtenez une remise de 15 % sur votre première commande.' },
{ keyword: 'panier d\'achat', response: 'Votre panier d\'achat est prêt pour le paiement.' },
{ keyword: 'test produit', response: 'Tous nos produits sont rigoureusement testés avant la mise en vente.' },
{ keyword: 'garantie', response: 'Le produit bénéficie d\'une garantie de 2 ans.' },
{ keyword: 'feedback', response: 'Nous apprécions votre retour d\'expérience pour améliorer nos services.' },
{ keyword: 'évaluation', response: 'Évaluez vos achats et laissez des commentaires pour aider les autres clients.' },
{ keyword: 'note', response: 'Notez ce produit pour nous aider à améliorer nos offres.' },
{ keyword: 'réservation', response: 'Réservez votre produit en ligne et retirez-le en magasin.' },
{ keyword: 'satisfaction', response: 'Votre satisfaction est notre priorité.' },
{ keyword: 'produit haut de gamme', response: 'Nous proposons des produits haut de gamme pour répondre à vos attentes.' },
{ keyword: 'produit exclusif', response: 'Ce produit est exclusif et disponible uniquement chez nous.' },
{ keyword: 'virement', response: 'Le paiement par virement bancaire est disponible.' },
{ keyword: 'commande reçue', response: 'Votre commande a été reçue et est en cours de traitement.' },
{ keyword: 'réponse rapide', response: 'Nous vous répondrons dans les plus brefs délais.' },
{ keyword: 'emballage', response: 'Tous nos produits sont soigneusement emballés pour garantir leur sécurité.' },
{ keyword: 'produit personnalisé', response: 'Créez un produit personnalisé selon vos préférences.' },
{ keyword: 'promotion', response: 'Actuellement, nous avons une promotion sur une sélection de produits.' },
{ keyword: 'partenaire', response: 'Nous collaborons avec des partenaires de confiance pour vous offrir le meilleur.' },
{ keyword: 'site web', response: 'Visitez notre site web pour découvrir tous nos produits.' },
{ keyword: 'nouveauté', response: 'Découvrez nos dernières nouveautés en ligne.' },
{ keyword: 'panier validé', response: 'Votre panier a été validé et est prêt pour le paiement.' },
{ keyword: 'produit épuisé', response: 'Ce produit est malheureusement épuisé pour le moment.' },
{ keyword: 'confirmation', response: 'Votre commande a bien été confirmée.' },
{ keyword: 'produit rare', response: 'Ce produit est rare et en quantité limitée.' },
{ keyword: 'recommandation', response: 'Nous vous recommandons ces produits en fonction de vos préférences.' },
{ keyword: 'produit défectueux', response: 'Si vous recevez un produit défectueux, veuillez nous en informer.' },
{ keyword: 'prix compétitif', response: 'Nous vous proposons des prix compétitifs sur tous nos produits.' },
{ keyword: 'retrait en magasin', response: 'Vous pouvez retirer votre commande directement en magasin.' },
{ keyword: 'livraison express', response: 'Choisissez la livraison express pour recevoir votre commande plus rapidement.' },
{ keyword: 'informations', response: 'Toutes les informations concernant votre commande sont disponibles dans votre compte.' },
{ keyword: 'produit à prix réduit', response: 'Ce produit est proposé à prix réduit pendant une durée limitée.' },
{ keyword: 'affichage', response: 'L\'affichage des produits sur le site est mis à jour régulièrement.' },
{ keyword: 'produit neuf', response: 'Nous proposons uniquement des produits neufs, jamais utilisés.' },
{ keyword: 'service après-vente', response: 'Notre service après-vente est à votre disposition pour toute question.' },
{ keyword: 'livraison retardée', response: 'Il y a un léger retard dans la livraison de votre commande.' },
{ keyword: 'problème de paiement', response: 'Si vous rencontrez un problème de paiement, contactez notre support.' },
{ keyword: 'moyens de paiement', response: 'Nous acceptons plusieurs moyens de paiement, dont les cartes bancaires et PayPal.' },
{ keyword: 'recommandé', response: 'Les produits recommandés sont sélectionnés en fonction de vos préférences.' },
{ keyword: 'réduction immédiate', response: 'Bénéficiez d\'une réduction immédiate sur votre prochaine commande.' },
{ keyword: 'service rapide', response: 'Nous nous efforçons de vous offrir un service rapide et efficace.' },
{ keyword: 'produit en stock', response: 'Le produit est actuellement en stock et disponible pour la commande.' },
{ keyword: 'produit en précommande', response: 'Vous pouvez précommander ce produit avant sa sortie officielle.' },
{ keyword: 'panier abandonné', response: 'Il semble que vous ayez abandonné votre panier. Souhaitez-vous finaliser votre commande ?' },
{ keyword: 'inscription', response: 'Inscrivez-vous pour bénéficier d\'offres exclusives et de réductions.' },
{ keyword: 'livraison suivie', response: 'Votre livraison peut être suivie en temps réel grâce à notre service de suivi.' },
{ keyword: 'évaluation produit', response: 'Évaluez vos produits pour aider d\'autres clients à faire leur choix.' },
{ keyword: 'retour produit', response: 'Vous pouvez retourner un produit dans les 30 jours suivant la réception.' },
{ keyword: 'produit recommandé', response: 'Ce produit est recommandé par nos experts.' },
{ keyword: 'produit en solde', response: 'Ce produit est actuellement en solde.' },
{ keyword: 'moyens de livraison', response: 'Nous proposons plusieurs moyens de livraison pour vous satisfaire.' },
{ keyword: 'moyen de paiement', response: 'Choisissez le moyen de paiement qui vous convient.' },
{ keyword: 'promotions spéciales', response: 'Ne manquez pas nos promotions spéciales sur une sélection de produits.' },
{ keyword: 'retour gratuit', response: 'Les retours sont gratuits pour les commandes dans un délai de 30 jours.' },
{ keyword: 'réduction fidélité', response: 'Les membres de notre programme de fidélité bénéficient de réductions exclusives.' },
{ keyword: 'produit premium', response: 'Nous proposons des produits premium pour répondre à vos exigences.' },
{ keyword: 'commande modifiée', response: 'Votre commande a été modifiée avec succès.' },
{ keyword: 'commande annulée', response: 'Votre commande a été annulée conformément à votre demande.' },
{ keyword: 'réduction immédiate', response: 'Bénéficiez d\'une réduction immédiate de 10 % sur votre commande.' },
{ keyword: 'carte cadeau', response: 'Offrez une carte cadeau à vos proches pour leur permettre de choisir leur propre cadeau.' },
{ keyword: 'retour produit', response: 'Vous pouvez demander un retour produit directement depuis votre compte.' },
{ keyword: 'livraison à domicile', response: 'Nous vous livrons directement à domicile dans les délais annoncés.' },
{ keyword: 'réduction pour étudiants', response: 'Les étudiants bénéficient d\'une réduction de 15 % sur leurs achats.' },
{ keyword: 'produit en rupture', response: 'Ce produit est actuellement en rupture de stock.' },
{ keyword: 'paiement sécurisé', response: 'Tous vos paiements sont sécurisés grâce à notre système de paiement sécurisé.' },
{ keyword: 'nouvelle collection', response: 'Découvrez notre nouvelle collection de produits exclusifs.' },
{ keyword: 'service personnalisé', response: 'Nous offrons un service personnalisé pour répondre à vos besoins.' },
{ keyword: 'code promo', response: 'Utilisez le code promo pour obtenir une réduction sur votre commande.' },
{ keyword: 'panier sauvegardé', response: 'Votre panier a été sauvegardé pour que vous puissiez revenir plus tard.' },
{ keyword: 'réduction solde', response: 'Les produits en solde bénéficient d\'une réduction supplémentaire de 10 %.' },
{ keyword: 'produit populaire', response: 'Ce produit est très populaire parmi nos clients.' },
{ keyword: 'avis client', response: 'Lisez les avis des autres clients avant de faire votre choix.' },
{ keyword: 'choisir taille', response: 'Choisissez votre taille avant d\'ajouter le produit au panier.' },
{ keyword: 'réductions exclusives', response: 'Profitez de réductions exclusives sur notre site pendant les soldes.' },
{ keyword: 'solde d\'hiver', response: 'Les soldes d\'hiver sont arrivées, avec des réductions allant jusqu\'à 50 %.' },
{ keyword: 'taille produit', response: 'Le produit est disponible en différentes tailles.' },
{ keyword: 'nouveau produit', response: 'Un nouveau produit est arrivé, n\'hésitez pas à le découvrir.' },
{ keyword: 'produit personnalisé', response: 'Créez un produit personnalisé pour une touche unique.' },
{ keyword: 'commande', response: 'Votre commande a bien été enregistrée.' },
{ keyword: 'produit', response: 'Le produit est en stock et prêt à être expédié.' },
{ keyword: 'paiement', response: 'Le paiement a été effectué avec succès.' },
{ keyword: 'livraison', response: 'La livraison est en cours et devrait arriver sous peu.' },
{ keyword: 'panier', response: 'Votre panier est actuellement vide.' },
{ keyword: 'offre', response: 'Profitez de notre offre spéciale avant qu\'elle n\'expire.' },
{ keyword: 'prix', response: 'Le prix du produit est affiché sur la page de chaque article.' },
{ keyword: 'réduction', response: 'Vous bénéficiez d\'une réduction de 20 % sur ce produit.' },
{ keyword: 'retour', response: 'Les retours sont acceptés dans les 30 jours suivant la réception.' },
{ keyword: 'remboursement', response: 'Votre remboursement sera traité dans un délai de 5 jours.' },
{ keyword: 'service', response: 'Notre service client est disponible pour répondre à vos questions.' },
{ keyword: 'contact', response: 'N\'hésitez pas à nous contacter si vous avez des questions.' },
{ keyword: 'disponibilité', response: 'Le produit est actuellement disponible en stock.' },
{ keyword: 'magasin', response: 'Le magasin est ouvert de 9h à 18h du lundi au vendredi.' },
{ keyword: 'carte', response: 'Vous pouvez payer avec votre carte bancaire.' },
{ keyword: 'abonnement', response: 'L\'abonnement à notre newsletter vous permet de recevoir des offres exclusives.' },
{ keyword: 'produits', response: 'Nous avons une large gamme de produits disponibles en ligne.' },
{ keyword: 'client', response: 'Nous vous remercions de votre fidélité en tant que client.' },
{ keyword: 'bénéfice', response: 'Profitez des avantages réservés aux membres du programme de fidélité.' },
{ keyword: 'assistance', response: 'Notre équipe d\'assistance est là pour vous aider en cas de besoin.' },
{ keyword: 'échange', response: 'Les échanges de produits sont possibles dans un délai de 30 jours.' },
{ keyword: 'remise', response: 'Obtenez une remise de 15 % sur votre première commande.' },
{ keyword: 'test', response: 'Tous nos produits sont rigoureusement testés avant la mise en vente.' },
{ keyword: 'garantie', response: 'Le produit bénéficie d\'une garantie de 2 ans.' },
{ keyword: 'feedback', response: 'Nous apprécions votre retour d\'expérience pour améliorer nos services.' },
{ keyword: 'évaluation', response: 'Évaluez vos achats et laissez des commentaires pour aider les autres clients.' },
{ keyword: 'note', response: 'Notez ce produit pour nous aider à améliorer nos offres.' },
{ keyword: 'réservation', response: 'Réservez votre produit en ligne et retirez-le en magasin.' },
{ keyword: 'satisfaction', response: 'Votre satisfaction est notre priorité.' },
{ keyword: 'produit', response: 'Nous proposons des produits haut de gamme pour répondre à vos attentes.' },
{ keyword: 'exclusif', response: 'Ce produit est exclusif et disponible uniquement chez nous.' },
{ keyword: 'virement', response: 'Le paiement par virement bancaire est disponible.' },
{ keyword: 'recommandation', response: 'Nous vous recommandons ces produits en fonction de vos préférences.' },
{ keyword: 'retard', response: 'Il y a un léger retard dans la livraison de votre commande.' },
{ keyword: 'informations', response: 'Toutes les informations concernant votre commande sont disponibles dans votre compte.' },
{ keyword: 'problème', response: 'Si vous rencontrez un problème de paiement, contactez notre support.' },
{ keyword: 'paiement', response: 'Tous vos paiements sont sécurisés grâce à notre système de paiement sécurisé.' },
{ keyword: 'réduction', response: 'Les produits en solde bénéficient d\'une réduction supplémentaire de 10 %.' },
{ keyword: 'produit', response: 'Ce produit est actuellement en rupture de stock.' },
{ keyword: 'livraison', response: 'Nous vous livrons directement à domicile dans les délais annoncés.' },
{ keyword: 'avis', response: 'Lisez les avis des autres clients avant de faire votre choix.' },
{ keyword: 'taille', response: 'Le produit est disponible en différentes tailles.' },
{ keyword: 'nouveau', response: 'Découvrez notre nouvelle collection de produits exclusifs.' },
{ keyword: 'carte', response: 'Offrez une carte cadeau à vos proches pour leur permettre de choisir leur propre cadeau.' },
{ keyword: 'retour', response: 'Vous pouvez demander un retour produit directement depuis votre compte.' },
{ keyword: 'livraison', response: 'Choisissez la livraison express pour recevoir votre commande plus rapidement.' },
{ keyword: 'produit', response: 'Ce produit est très populaire parmi nos clients.' },
{ keyword: 'choisir', response: 'Choisissez votre taille avant d\'ajouter le produit au panier.' },
{ keyword: 'réductions', response: 'Profitez de réductions exclusives sur notre site pendant les soldes.' },
{ keyword: 'solde', response: 'Les soldes d\'hiver sont arrivées, avec des réductions allant jusqu\'à 50 %.' },
{ keyword: 'produit', response: 'Ce produit est proposé à prix réduit pendant une durée limitée.' },
{ keyword: 'offre', response: 'Ne manquez pas nos promotions spéciales sur une sélection de produits.' },
{ keyword: 'réduction', response: 'Bénéficiez d\'une réduction immédiate de 10 % sur votre commande.' },
{ keyword: 'promotion', response: 'Les promotions sont mises à jour chaque semaine.' },
{ keyword: 'panier', response: 'Votre panier a été sauvegardé pour que vous puissiez revenir plus tard.' },
{ keyword: 'solde', response: 'Les produits en solde bénéficient d\'une réduction supplémentaire de 10 %.' },
{ keyword: 'commande', response: 'Votre commande a été expédiée et est en chemin.' },
{ keyword: 'produit', response: 'Nous proposons uniquement des produits neufs, jamais utilisés.' },
{ keyword: 'service', response: 'Notre service après-vente est à votre disposition pour toute question.' },
{ keyword: 'produit', response: 'Les produits sont soigneusement emballés pour garantir leur sécurité.' },
{ keyword: 'évaluation', response: 'Les évaluations de produits aident d\'autres clients à faire leur choix.' },
{ keyword: 'stock', response: 'Les produits en stock sont disponibles pour une livraison rapide.' },
{ keyword: 'panier', response: 'Ajoutez des produits à votre panier pour commencer votre achat.' },
{ keyword: 'avis', response: 'Laissez un avis pour partager votre expérience avec d\'autres utilisateurs.' },
{ keyword: 'code', response: 'Utilisez le code promo pour obtenir une réduction sur votre commande.' },
{ keyword: 'commande', response: 'Modifiez votre commande avant la confirmation du paiement.' },
{ keyword: 'produit', response: 'Les produits sont testés pour garantir leur qualité.' },
{ keyword: 'cartes', response: 'Nous acceptons les cartes Visa et MasterCard.' },
{ keyword: 'système', response: 'Le système de paiement est entièrement sécurisé.' },
{ keyword: 'retrait', response: 'Retirez votre commande directement en magasin pour plus de commodité.' },
{ keyword: 'panier', response: 'Vous pouvez modifier le contenu de votre panier à tout moment.' },
{ keyword: 'panier', response: 'Votre panier est vide, ajoutez des articles pour commencer.' },
{ keyword: 'produits', response: 'Nous avons une large gamme de produits pour répondre à tous vos besoins.' },
{ keyword: 'produit', response: 'Nous avons plusieurs modèles de produits disponibles.' },
{ keyword: 'livraison', response: 'La livraison à domicile est disponible dans votre région.' },
{ keyword: 'remise', response: 'Bénéficiez d\'une remise de 10 % sur vos achats en ligne.' },
{ keyword: 'panier', response: 'Complétez votre panier et profitez de la livraison gratuite.' },
{ keyword: 'produit', response: 'Ce produit est en rupture de stock pour le moment.' },
{ keyword: 'nouveauté', response: 'Découvrez nos nouveautés en avant-première.' },
{ keyword: 'test', response: 'Tous nos produits sont testés pour assurer leur qualité.' },
{ keyword: 'produit', response: 'Nous proposons une garantie sur tous nos produits.' },
{ keyword: 'produit', response: 'Le produit que vous cherchez est disponible en plusieurs tailles.' },
{ keyword: 'réduction', response: 'Des réductions sont disponibles pour les membres inscrits.' },
{ keyword: 'service', response: 'Notre service client est disponible pour répondre à toutes vos questions.' },
{ keyword: 'offre', response: 'Profitez de nos offres spéciales cette semaine.' },
{ keyword: 'site', response: 'Visitez notre site pour découvrir nos produits.' },
{ keyword: 'produits', response: 'Nous avons une vaste sélection de produits pour répondre à vos besoins.' },
{ keyword: 'panier', response: 'Ajoutez des produits à votre panier pour pouvoir passer à la caisse.' },
{ keyword: 'annulation', response: 'Vous pouvez annuler votre commande avant son expédition.' },
{ keyword: 'panier', response: 'Votre panier contient actuellement 5 articles.' },
{ keyword: 'panier', response: 'Votre panier est prêt à être validé.' },
{ keyword: 'livraison', response: 'Les frais de livraison sont calculés au moment de la commande.' },
{ keyword: 'produit', response: 'Le produit est actuellement en rupture de stock.' },
{ keyword: 'prix', response: 'Le prix total de votre commande est de 50 €.' },
{ keyword: 'commande', response: 'Votre commande a été confirmée et sera traitée prochainement.' },
{ keyword: 'évaluation', response: 'Laissez une évaluation pour aider les autres acheteurs.' },
{ keyword: 'service', response: 'Notre service client est à votre disposition pour toute question.' },
{ keyword: 'solde', response: 'Le solde de votre compte est de 20 €.' },
{ keyword: 'code', response: 'Entrez le code promo pour bénéficier de 10 % de réduction.' },
{ keyword: 'abonnement', response: 'Souscrivez à notre abonnement pour recevoir des offres exclusives.' },
{ keyword: 'réduction', response: 'Bénéficiez de 20 % de réduction sur votre première commande.' },
{ keyword: 'échange', response: 'L\'échange est accepté dans un délai de 30 jours.' },
{ keyword: 'partenaire', response: 'Nous collaborons avec divers partenaires pour vous offrir les meilleures offres.' },
{ keyword: 'garantie', response: 'Le produit bénéficie d\'une garantie de 2 ans contre les défauts de fabrication.' },
{ keyword: 'annulation', response: 'Vous pouvez annuler votre commande dans un délai de 24 heures.' },
{ keyword: 'facture', response: 'La facture de votre commande vous sera envoyée par email.' },
{ keyword: 'retour', response: 'Le retour des produits est accepté dans un délai de 30 jours.' },
{ keyword: 'avis', response: 'Consultez les avis avant d\'effectuer votre achat.' },
{ keyword: 'expédition', response: 'L\'expédition de votre commande est en cours.' },
{ keyword: 'site', response: 'Le site est sécurisé pour garantir la protection de vos données.' },
{ keyword: 'programme', response: 'Notre programme de fidélité vous permet de cumuler des points sur vos achats.' },
{ keyword: 'cartes', response: 'Nous acceptons les paiements par cartes bancaires et PayPal.' },
{ keyword: 'méthode', response: 'Nous proposons plusieurs méthodes de paiement pour plus de flexibilité.' },
{ keyword: 'expédition', response: 'Votre commande sera expédiée dans les plus brefs délais.' },
{ keyword: 'contact', response: 'Contactez-nous via notre formulaire ou par téléphone.' },
{ keyword: 'produits', response: 'Tous nos produits sont soigneusement sélectionnés et vérifiés.' },
{ keyword: 'compte', response: 'Connectez-vous à votre compte pour finaliser votre commande.' },
{ keyword: 'stock', response: 'Le produit est actuellement en stock et prêt à être expédié.' },
{ keyword: 'retour', response: 'Les retours sont gratuits dans les 30 jours suivant la réception.' },
{ keyword: 'annuler', response: 'Vous pouvez annuler votre commande avant l\'expédition.' },
{ keyword: 'connexion', response: 'Connectez-vous à votre compte pour voir vos commandes passées.' },
{ keyword: 'réclamation', response: 'Soumettez une réclamation si vous avez rencontré un problème avec votre commande.' },
{ keyword: 'réponse', response: 'Nous vous répondrons dans les plus brefs délais.' },
{ keyword: 'assistance', response: 'Notre équipe d\'assistance est disponible pour vous aider.' },
{ keyword: 'mode', response: 'Explorez notre nouvelle collection en mode printemps-été.' },
{ keyword: 'programme', response: 'Rejoignez notre programme de fidélité pour obtenir des réductions.' },
{ keyword: 'produit', response: 'Ce produit est en rupture de stock pour l\'instant.' },
{ keyword: 'coup', response: 'Profitez de notre offre exceptionnelle, valable pour un temps limité.' },
{ keyword: 'panier', response: 'Votre panier contient actuellement 3 articles.' },
{ keyword: 'promotion', response: 'Bénéficiez d\'une promotion spéciale en cette période de soldes.' },
{ keyword: 'envoi', response: 'L\'envoi de votre commande est en cours.' },
{ keyword: 'avantage', response: 'En tant que membre, vous bénéficiez de nombreux avantages.' },
{ keyword: 'produit', response: 'Les produits sont disponibles en plusieurs tailles et couleurs.' },
{ keyword: 'confirmation', response: 'Vous recevrez une confirmation de commande par email.' },
{ keyword: 'retrait', response: 'Vous pouvez retirer votre commande en magasin.' },
{ keyword: 'code', response: 'Entrez le code promo pour bénéficier d\'une remise de 15 %.' },
{ keyword: 'offre', response: 'Découvrez notre nouvelle offre exclusive en ligne.' },
{ keyword: 'remise', response: 'Une remise de 10 % est appliquée à votre commande.' },
{ keyword: 'remboursement', response: 'Le remboursement sera effectué sous 7 jours.' },
{ keyword: 'boutique', response: 'La boutique est uniquement en ligne pour l\'instant.' },
{ keyword: 'produit', response: 'Le produit est disponible en stock.' },
{ keyword: 'disponibilité', response: 'Le produit est en rupture de stock pour l\'instant.' },
{ keyword: 'délais', response: 'Les délais de livraison peuvent varier selon votre localisation.' },
{ keyword: 'point', response: 'Cumulez des points avec chaque achat.' },
{ keyword: 'inscription', response: 'Inscrivez-vous pour recevoir nos promotions exclusives.' },
{ keyword: 'assurance', response: 'L\'assurance est incluse pour les livraisons internationales.' },
{ keyword: 'satisfaction', response: 'Votre satisfaction est notre priorité.' },
{ keyword: 'service', response: 'Notre service clientèle est là pour vous assister.' },
{ keyword: 'reduction', response: 'Une réduction de 20 % est offerte sur vos achats.' },
{ keyword: 'réserve', response: 'Réservez dès maintenant vos articles préférés.' },
{ keyword: 'prix', response: 'Les prix sont affichés en fonction de la sélection des produits.' },
{ keyword: 'choix', response: 'Faites votre choix parmi une large sélection.' },
{ keyword: 'panier', response: 'Votre panier est vide, il est temps d\'ajouter des articles.' },
{ keyword: 'téléphone', response: 'Appelez notre service clientèle pour toute assistance.' },
{ keyword: 'question', response: 'Vous avez une question ? Notre équipe est là pour vous répondre.' },
{ keyword: 'carte', response: 'Nous acceptons les cartes bancaires pour le paiement.' },
{ keyword: 'retrait', response: 'Retirer vos articles en magasin est possible.' },
{ keyword: 'produit', response: 'Tous nos produits sont soigneusement vérifiés avant l\'expédition.' },
{ keyword: 'service', response: 'Le service est disponible pour résoudre tout problème.' },
{ keyword: 'carte', response: 'Les cartes cadeaux sont disponibles sur notre site.' },
{ keyword: 'expédition', response: 'Votre commande a été expédiée et sera livrée sous 3 jours.' },
{ keyword: 'nouveau', response: 'Découvrez nos nouveautés chaque semaine.' },
{ keyword: 'récompense', response: 'Recevez des récompenses pour chaque achat effectué.' },
{ keyword: 'sécurité', response: 'Votre sécurité est notre priorité lors de vos achats.' },
{ keyword: 'retour', response: 'Les retours sont acceptés dans les 30 jours suivant la réception.' },
{ keyword: 'panier', response: 'Ajoutez des articles à votre panier pour les acheter plus tard.' },
{ keyword: 'promotion', response: 'Consultez nos promotions actuelles pour économiser.' },
{ keyword: 'carte', response: 'Les cartes bancaires sont acceptées pour les paiements.' },
{ keyword: 'expédition', response: 'L\'expédition des produits est gratuite à partir de 50 € d\'achat.' },
{ keyword: 'produit', response: 'Les produits en vente sont limités en stock.' },
{ keyword: 'commande', response: 'La commande est en préparation.' },
{ keyword: 'offre', response: 'Profitez de notre offre d\'adhésion pour des réductions.' },
{ keyword: 'réclamation', response: 'Soumettez une réclamation si nécessaire.' },
{ keyword: 'retrait', response: 'Retirez vos achats en magasin ou faites-les livrer.' },
{ keyword: 'assurance', response: 'L\'assurance de votre produit peut être ajoutée lors de l\'achat.' },
{ keyword: 'solde', response: 'Le solde restant est visible dans votre compte.' },
{ keyword: 'évaluation', response: 'Évaluez vos achats pour aider les autres clients.' },
{ keyword: 'service', response: 'Notre service client est disponible 24/7 pour vous aider.' },
{ keyword: 'produit', response: 'Le produit est en rupture de stock mais sera réapprovisionné bientôt.' },
{ keyword: 'panier', response: 'Ajoutez des articles à votre panier pour les acheter plus tard.' },
{ keyword: 'site', response: 'Le site est optimisé pour une navigation rapide.' },
{ keyword: 'offre', response: 'Découvrez notre offre spéciale de la semaine.' },
{ keyword: 'avantage', response: 'Profitez des avantages réservés aux membres.' },
{ keyword: 'téléphone', response: 'Vous pouvez nous joindre au numéro de téléphone indiqué.' }



  ];

  constructor() {}

  sendMessage(): void {
    if (this.userMessage.trim()) {
      this.messages.push({ user: this.userMessage, bot: '' });
      this.getBotResponse(this.userMessage.toLowerCase()).then(response => {
        this.messages[this.messages.length - 1].bot = response;
      });
      this.userMessage = '';  // Réinitialiser le champ de saisie
    }
  }

  // Fonction pour obtenir la réponse basée sur la correspondance avec les mots-clés
  private async getBotResponse(message: string): Promise<string> {
    let response = 'Désolé, je n\'ai pas compris votre question.';

    for (const data of this.responseDatabase) {
      if (message.includes(data.keyword)) {
        response = data.response;
        break;
      }
    }

    return response;
  }

  // Gérer l'événement "Entrée" dans le champ de saisie
  onEnter(event: KeyboardEvent): void {
    if (event.key === 'Enter') {
      this.sendMessage();
    }
  }

  // Méthode pour fermer le chatbot
  closeChatbot(): void {
    this.isChatbotVisible = false;  // Cacher le chatbot
  }
}
